### ISSUE TITLE
Document workflow on how to generate this data

### ISSUE THREAD

**Issue by leonardehrenfried** [yetzt/postleitzahlen#1]
Hi, thanks for generating the PLZ data!

I'd be very interested to learn how to generate the geojson myself.

Would you mind sharing how you did it?

**Comment by yetzt** [comment]
@lenniboy thb, i don't remember, since this is just sample data for testing the idea of [open data repositories](https://github.com/yetzt/odr) vs [data packages](http://specs.frictionlessdata.io/data-packages/). sorry.

**Comment by baslr** [comment]
@leonardehrenfried soweit ich das verstehe https://wiki.openstreetmap.org/wiki/DE:Konsolidierung_der_PLZ-Relationen_in_Deutschland_2013
werden/sind die PLZ-Gebiete entkoppelt. Müsste sich somit aus dem OSM-Deutschlanddatensatz extrahieren lassen.

**Comment by yetzt** [comment]
Ich habe den Overpass-Query, den ich im aktuellen update verwendet habe, im README dokumentiert.

**Comment by leonardehrenfried** [comment]
OMG, a blast from the past. Thank you!
